from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("landlord/properties/new/", views.add_property, name="landlord-add-property"),
    path("landlord/properties/<int:property_id>/", views.property_detail, name="landlord-property-detail"),
    path("landlord/properties/<int:property_id>/edit/", views.edit_property, name="landlord-edit-property"),
    path("landlord/properties/<int:property_id>/delete/", views.delete_property, name="landlord-delete-property"),
    path("landlord/dashboard/", views.landlord_page, {"page": "overview"}, name="landlord-dashboard"),
    path("landlord/overview/", views.landlord_page, {"page": "overview"}, name="landlord-overview"),
    path("landlord/properties/", views.landlord_page, {"page": "properties"}, name="landlord-properties"),
    path("landlord/tenants/new/", views.add_tenant, name="landlord-add-tenant"),
    path("landlord/tenants/extensions/<int:extension_request_id>/", views.landlord_extension_request_detail, name="landlord-extension-request-detail"),
    path("landlord/tenants/<int:tenant_id>/", views.tenant_detail, name="landlord-tenant-detail"),
    path("landlord/tenants/<int:tenant_id>/edit/", views.edit_tenant, name="landlord-edit-tenant"),
    path("landlord/tenants/<int:tenant_id>/delete/", views.delete_tenant, name="landlord-delete-tenant"),
    path("landlord/tenants/", views.landlord_page, {"page": "tenants"}, name="landlord-tenants"),
    path("landlord/payments/new/", views.record_payment, name="landlord-record-payment"),
    path("landlord/payments/<int:payment_id>/approve/", views.approve_payment, name="landlord-approve-payment"),
    path("landlord/payments/<int:payment_id>/", views.landlord_payment_detail, name="landlord-payment-detail"),
    path("landlord/payments/", views.landlord_page, {"page": "payments"}, name="landlord-payments"),
    path("landlord/bills/new/", views.add_bill, name="landlord-add-bill"),
    path("landlord/bills/<int:bill_id>/", views.landlord_bill_detail, name="landlord-bill-detail"),
    path("landlord/bills/", views.landlord_page, {"page": "bills"}, name="landlord-bills"),
    path("landlord/maintenance/<int:complaint_id>/", views.complaint_detail, name="landlord-complaint-detail"),
    path("landlord/maintenance/", views.landlord_page, {"page": "maintenance"}, name="landlord-maintenance"),
    path("landlord/analytics/", views.landlord_page, {"page": "analytics"}, name="landlord-analytics"),
    path("landlord/notifications/", views.landlord_page, {"page": "notifications"}, name="landlord-notifications"),
    path("landlord/notifications/<int:notification_id>/read/", views.mark_notification_read_view, name="landlord-mark-notification-read"),
    path("landlord/notifications/read-all/", views.mark_all_notifications_read_view, name="landlord-mark-all-notifications-read"),
    path("landlord/settings/", views.landlord_settings, name="landlord-settings"),
    path("tenant/dashboard/", views.tenant_page, {"page": "overview"}, name="tenant-dashboard"),
    path("tenant/overview/", views.tenant_page, {"page": "overview"}, name="tenant-overview"),
    path("tenant/receipts/", views.tenant_receipts, name="tenant-receipts"),
    path("tenant/receipts/bills/<int:bill_id>/", views.tenant_bill_detail, name="tenant-bill-detail"),
    path("tenant/receipts/payments/<int:payment_id>/", views.tenant_payment_detail, name="tenant-payment-detail"),
    path("tenant/profile/", views.tenant_profile, name="tenant-profile"),
    path("tenant/complaints/", views.tenant_complaints, name="tenant-complaints"),
    path("tenant/complaints/<int:complaint_id>/", views.tenant_complaint_detail, name="tenant-complaint-detail"),
    path("tenant/notifications/", views.tenant_page, {"page": "notifications"}, name="tenant-notifications"),
    path("tenant/notifications/<int:notification_id>/read/", views.mark_notification_read_view, name="tenant-mark-notification-read"),
    path("tenant/notifications/read-all/", views.mark_all_notifications_read_view, name="tenant-mark-all-notifications-read"),
    path("tenant/analytics/", views.tenant_page, {"page": "analytics"}, name="tenant-analytics"),
    path("tenant/settings/", views.tenant_settings, name="tenant-settings"),
]
