# Generated by Django 4.2.29 on 2026-04-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('units', models.PositiveIntegerField()),
                ('occupied_units', models.PositiveIntegerField()),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occupancy', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('High Performing', 'High Performing'), ('Stable', 'Stable'), ('Needs Attention', 'Needs Attention'), ('Vacancy Risk', 'Vacancy Risk')], default='Stable', max_length=32)),
                ('trend', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
