# Generated by Django 4.2.29 on 2026-04-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupied_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PropertyUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=120)),
                ('unit_count', models.PositiveIntegerField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='accounts.property')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
