# Generated by Django 4.2.29 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_complaint_status_payment_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
