# Generated by Django 4.2.29 on 2026-04-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bill_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
    ]
