# Generated by Django 4.2.29 on 2026-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_rent_charge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
