# Generated by Django 4.2.29 on 2026-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tenant_last_rent_charge_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='autopay_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='autopay_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='autopay_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='autopay_card_expiry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='autopay_card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
