# Generated by Django 4.2.29 on 2026-05-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tenant_autopay_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_periods',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='scope',
            field=models.CharField(choices=[('Bill', 'Specific Bill'), ('Rent', 'Rent'), ('All', 'All Open Bills')], default='All', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
