# Generated by Django 4.2.29 on 2026-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_payment_bill_payment_rent_periods_payment_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='selected_bill_ids',
            field=models.TextField(blank=True),
        ),
    ]
