# Generated by Django 4.2.29 on 2026-05-06 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_complaint_landlord_notes_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_bearer', models.CharField(choices=[('Tenant', 'Tenant'), ('Management', 'Management'), ('Landlord', 'Landlord')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_expense', to='accounts.bill')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.complaint')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
