# Generated by Django 4.2.29 on 2026-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_paymentallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseextensionrequest',
            name='landlord_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaseextensionrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
