# Generated by Django 4.2.29 on 2026-05-07 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_leaseextensionrequest_landlord_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('owner_digest_enabled', models.BooleanField(default=True)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
                ('maintenance_escalation_enabled', models.BooleanField(default=True)),
                ('autopay_nudges_enabled', models.BooleanField(default=False)),
                ('rent_reminder_days', models.PositiveSmallIntegerField(default=5)),
                ('overdue_follow_up_days', models.PositiveSmallIntegerField(default=2)),
                ('maintenance_escalation_hours', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landlord settings',
                'verbose_name_plural': 'Landlord settings',
            },
        ),
    ]
